version: 2
jobs:
  build:
    docker:
      - image: python:3.6.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
            pip install coverage==5.0.4
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run tests
          command: |
            set -xu
            ./cc-test-reporter before-build
            ./tests.sh
            coverage combine
            coverage xml
            ./cc-test-reporter after-build --exit-code $?
